Repository MTrab/pyworxcloud, pull requests merged in 2023-04, with the labels that each got.

#121 Try fixing requirements
  poetry.lock
  pyproject.toml
  pyworxcloud/utils/mqtt.py
  test.py
Labels: bug, patch

#122 Moving to Paho-MQTT
  poetry.lock
  pyproject.toml
  pyworxcloud/__init__.py
  pyworxcloud/utils/mqtt.py
  test_async.py
Labels: enhancement, minor

#124 Update QoS flag
  .vscode/settings.json
  pyworxcloud/utils/mqtt.py
Labels: enhancement, patch

#125 Enable reconnect and MQTT events
  pyworxcloud/exceptions.py
  pyworxcloud/utils/mqtt.py
Labels: enhancement

#126 Fixing connection check issues
  pyworxcloud/__init__.py
  pyworxcloud/utils/mqtt.py
Labels: bug

#127 Add token update on MQTT disconnect
  pyworxcloud/__init__.py
  pyworxcloud/utils/mqtt.py
Labels: bug

#119 fix auto_schedule mapping
  pyworxcloud/utils/devices.py
  pyworxcloud/utils/schedules.py
Labels: bug

#118 bugfix on rain_delay & toggle_schedule
  pyworxcloud/__init__.py
Labels: bug

#132 Fix wrong Python requirement
  pyproject.toml
  pyworxcloud/__init__.py
Labels: bug

#134 Fix-timeout-handling
  pyworxcloud/exceptions.py
  pyworxcloud/utils/requests.py
Labels: bug

#135 Adding model info
  pyworxcloud/api.py
  pyworxcloud/utils/devices.py
Labels: enhancement

#136 Fixing issue using disconnect function
  pyworxcloud/utils/mqtt.py
Labels: bug
