Repository MTrab/pyworxcloud, pull requests merged in 2023-11, with the labels that each got.

#184 Add initial Kress Mission RTK support
  pyworxcloud/__init__.py
Labels: enhancement, minor

#185 Fixing dataset matching for Kress
  pyworxcloud/__init__.py
Labels: bug

#186 Handle unknown state ID
  pyworxcloud/utils/state.py
Labels: bug, patch

#187 Do not change status ID
  pyworxcloud/utils/state.py
Labels: enhancement, patch

#188 Adding extra state IDs for Kress Mission
  pyworxcloud/utils/state.py
Labels: enhancement, patch

#189 Multiple fixes in new protocol matching and handling
  pyworxcloud/__init__.py
  pyworxcloud/utils/capability.py
  pyworxcloud/utils/mqtt.py
  pyworxcloud/utils/state.py
  test.py
Labels: bug, patch

#190 Unified update timestamp
  old_version/__init__.py
  old_version/api.py
  old_version/clouds.py
  old_version/const.py
  old_version/day_map.py
  old_version/events.py
  old_version/exceptions.py
  old_version/helpers/__init__.py
  old_version/helpers/logger.py
  old_version/helpers/time_format.py
  old_version/utils/__init__.py
  old_version/utils/actions.py
  old_version/utils/battery.py
  old_version/utils/blades.py
  old_version/utils/capability.py
  old_version/utils/devices.py
  old_version/utils/firmware.py
  old_version/utils/landroid_class.py
  old_version/utils/lawn.py
  old_version/utils/location.py
  old_version/utils/mqtt.py
  old_version/utils/orientation.py
  old_version/utils/product.py
  old_version/utils/rainsensor.py
  old_version/utils/schedules.py
  old_version/utils/state.py
  old_version/utils/statistics.py
  old_version/utils/warranty.py
  old_version/utils/zone.py
  pyworxcloud/__init__.py
  test.py
Labels: bug, patch

#192 Fix missing gps key in early startup phase
  pyworxcloud/__init__.py
Labels: bug, patch

#193 Use correct timezone data in 'updated' property
  pyworxcloud/__init__.py
Labels: enhancement, patch

#194 Fixing broken update attribute
  pyworxcloud/__init__.py
  test.py
Labels: bug

#195 Protocol 1 devices reports update in UTC
  pyworxcloud/__init__.py
Labels: bug, patch
