Repository MTrab/pyworxcloud, pull requests merged in 2023-05, with the labels that each got.

#141 Fixing bug in setzone call
  pyworxcloud/__init__.py
  pyworxcloud/utils/devices.py
  pyworxcloud/utils/zone.py
  test.py
Labels: bug

#142 Identify using MAC address if serial not present
  pyworxcloud/__init__.py
  test.py
Labels: enhancement

#143 Catch JSONDecodeError to prevent crash on malformed message
  pyworxcloud/__init__.py
Labels: bug

#139 Fix decode secondary schedule
  pyworxcloud/__init__.py
Labels: bug

#144 Fixing race on zone with no probability
  pyworxcloud/__init__.py
  pyworxcloud/exceptions.py
Labels: bug

#145 Catch authorization error
  pyworxcloud/api.py
Labels: enhancement

#147 Only set raw_data if last_status is not None
  pyworxcloud/__init__.py
Labels: bug

#149 Adding check for data in last_status
  pyworxcloud/utils/zone.py
Labels: bug

#151 Bump requests
  poetry.lock
  pyproject.toml
Labels: dependencies, patch

#153 Switch to global SSO domains
  pyworxcloud/clouds.py
Labels: enhancement

#154 Downgrade requests requirement
  poetry.lock
  pyproject.toml
Labels: bug

#157 Try handling disconnects on error
  pyworxcloud/utils/mqtt.py
Labels: enhancement

#158 Check if mowers are available
  pyworxcloud/__init__.py
Labels: enhancement

#159 Add forced refresh scheduling
  pyworxcloud/__init__.py
Labels: enhancement

#161 Add try-except on decode data
  pyworxcloud/__init__.py
  pyworxcloud/exceptions.py
  pyworxcloud/utils/zone.py
Labels: enhancement

#160 handle disconnect when no mower in account
  pyworxcloud/__init__.py
Labels: bug

#163 Add try-except on disconnect
  pyworxcloud/__init__.py
  pyworxcloud/utils/zone.py
Labels: enhancement
