Repository MTrab/pyworxcloud, pull requests merged in 2025-02, with the labels that each got.

#218 Fix API data refresh
  .vscode/launch.json
  pyworxcloud/__init__.py
  pyworxcloud/api.py
  pyworxcloud/events.py
  pyworxcloud/utils/devices.py
  test.py
  test_async.py
  test_with.py
Labels: minor

#219 Update release-dreafter template
  .github/release-drafter.yml
Labels: patch, skip-changelog

#220 Update dependency requirements for HA 2025.3
  pyproject.toml
Labels: patch
